services:
  valhalla:
    image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
    container_name: valhalla
    ports:
      - "8002:8002"
    volumes:
      - ./custom_files:/custom_files
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    entrypoint: ["bash","-lc","valhalla_service /custom_files/valhalla.json 1"]
    restart: unless-stopped
